chore: initial gitlab setup
taxfix/docker-node-libvips pull request #2
Opened 2021-08-18 13:49 UTC by MetCoder95

2021-08-20 08:29 UTC, ngoduykhanh requested changes

2021-08-20 08:29 UTC, ngoduykhanh commented on .gitlab-ci.yml
> +    name: preview
As far as I understand, this pipeline setup is just for building and pushing the docker image.
Do we need the `deploy-preview`, `deploy-integration`, `deploy-staging` and `deploy-production` here?

2021-08-20 08:29 UTC, ngoduykhanh commented on .gitlab-ci.yml
> +      export REGISTRY_IMAGE_LATEST=${REGISTRY_URL}/$PROJECT_NAME/${CI_PROJECT_NAME}:latest
I think this script needs to be adjusted as well. Let's remove unnecessary code, e.g mono-repo, preview?

2021-08-20 08:29 UTC, ngoduykhanh commented on .gitlab-ci.yml
> +  DOCKER_HOST: "tcp://docker:2375"
Set `DOCKER_HOST: "tcp://dind:2375"` will help the pipeline to use the Docker layer caching.

2021-08-20 09:24 UTC, MetCoder95 commented on .gitlab-ci.yml
> +    name: preview
You're right, but my idea was to have the chance to properly test it out in the same way as a single service. So if you want to e.g.  **test your docker image and see how it behaves on the cluster**, might be good to have a chance to do so.
Maybe you're right, two steps can be removed like `integration` and `staging`. But `preview` can be nice to have so we can directly test it out. What do you think?

2021-08-20 09:25 UTC, MetCoder95 commented on .gitlab-ci.yml
> +      export REGISTRY_IMAGE_LATEST=${REGISTRY_URL}/$PROJECT_NAME/${CI_PROJECT_NAME}:latest
You're right, didn't do cleanup 🙏

2021-08-20 09:26 UTC, MetCoder95 commented on .gitlab-ci.yml
> +  DOCKER_HOST: "tcp://docker:2375"
I knew I was missing something for caching 😅

2021-08-20 14:23 UTC, MetCoder95 commented on .gitlab-ci.yml
> +    name: preview
I removed `integration` and `staging`, hope is ok 😄

2021-08-20 14:41 UTC, MetCoder95 commented
I cannot ask to for another review but can you take a second look? @ngoduykhanh 🙏

2021-08-23 14:23 UTC, MetCoder95 commented
Merging now, if you have more feedback please feel free to make it, I'll apply them when creating `hades` repo 👍

2021-08-23 14:23 UTC, merged